#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# SLUCM smoke test driver.
#
# Runs the same 10 x 10 x 20 synthetic urban case twice -- once with
# SF_URBAN_PHYSICS = 1 (urban tile on) and once with 0 (Noah-MP bulk-urban
# control) -- and hands both to check_smoke.py.
#
#   ./run_smoke.sh --exe /path/to/erf_exec [--work DIR] [--np N] [--no-check]
#
# Everything the runs need is staged from the source tree: the synthetic
# wrfinput is generated by Tests/Utils/make_synthetic_wrfinput.py, the Noah-MP
# tables come from Submodules/Noah-MP/drivers/erf, and the four RRTMGP
# coefficient files come from Submodules/RRTMGP.  Nothing is downloaded.
# ---------------------------------------------------------------------------
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
ERF_ROOT=$(cd "$SCRIPT_DIR/../../.." && pwd)

EXE=""
WORK="$PWD/slucm_smoke"
NP=1
RUN_CHECK=1

while [ $# -gt 0 ]; do
    case "$1" in
        --exe)      EXE=$2;   shift 2 ;;
        --work)     WORK=$2;  shift 2 ;;
        --np)       NP=$2;    shift 2 ;;
        --no-check) RUN_CHECK=0; shift ;;
        -h|--help)  sed -n '2,17p' "$0"; exit 0 ;;
        *) echo "unknown argument: $1" >&2; exit 2 ;;
    esac
done

if [ -z "$EXE" ]; then
    echo "ERROR: --exe <path to erf_exec> is required" >&2
    exit 2
fi
EXE=$(cd "$(dirname "$EXE")" && pwd)/$(basename "$EXE")
[ -x "$EXE" ] || { echo "ERROR: $EXE is not executable" >&2; exit 2; }

# The domain is 10 cells wide and may only be split in x (see the mpirun call
# below), so --np must divide 10.
MGS_X=10
if [ "$NP" -gt 1 ]; then
    if [ $((10 % NP)) -ne 0 ]; then
        echo "ERROR: --np must divide the 10-cell x extent (try 1, 2, 5 or 10)" >&2
        exit 2
    fi
    MGS_X=$((10 / NP))
fi

NOAHMP_DRV=$ERF_ROOT/Submodules/Noah-MP/drivers/erf
RRTMGP=$ERF_ROOT/Submodules/RRTMGP
for f in "$NOAHMP_DRV/NoahmpTable.TBL" "$NOAHMP_DRV/URBPARM.TBL" \
         "$RRTMGP/rrtmgp/data/rrtmgp-data-sw-g224-2018-12-04.nc" \
         "$RRTMGP/rrtmgp/data/rrtmgp-data-lw-g256-2018-12-04.nc" \
         "$RRTMGP/extensions/cloud_optics/rrtmgp-cloud-optics-coeffs-sw.nc" \
         "$RRTMGP/extensions/cloud_optics/rrtmgp-cloud-optics-coeffs-lw.nc"; do
    [ -f "$f" ] || { echo "ERROR: missing $f (submodules initialised?)" >&2; exit 2; }
done

rm -rf "$WORK"
mkdir -p "$WORK"

# The date here must match START_* in namelist.erf.  19 Z at longitude -105 is
# local solar noon.
echo "[smoke] generating synthetic wrfinput"
# The 1 m/s wind is deliberate: it keeps the surface layer non-degenerate while
# holding the urban signal inside its own cells for the first land sample,
# which is what makes check_smoke.py's rural-quiescence assertion meaningful.
python3 "$ERF_ROOT/Tests/Utils/make_synthetic_wrfinput.py" \
    -o "$WORK/wrfinput_urban_d01" \
    --start-date 2020-07-01_19:00:00 --julyr 2020 --julday 183 --gmt 19.0 \
    --lat 40.0 --lon -105.0 --u 1.0 --v 0.0 \
    > "$WORK/make_wrfinput.log"

for CASE in urban rural; do
    RUNDIR=$WORK/$CASE
    mkdir -p "$RUNDIR"
    cp "$WORK/wrfinput_urban_d01" "$RUNDIR/"
    cp "$SCRIPT_DIR/inputs_slucm" "$RUNDIR/"
    if [ "$CASE" = urban ]; then
        cp "$SCRIPT_DIR/namelist.erf" "$RUNDIR/namelist.erf"
    else
        sed 's/^ SF_URBAN_PHYSICS = 1/ SF_URBAN_PHYSICS = 0/' \
            "$SCRIPT_DIR/namelist.erf" > "$RUNDIR/namelist.erf"
        grep -q "SF_URBAN_PHYSICS = 0" "$RUNDIR/namelist.erf" \
            || { echo "ERROR: control namelist rewrite failed" >&2; exit 1; }
    fi
    ln -sf "$NOAHMP_DRV/NoahmpTable.TBL" "$RUNDIR/NoahmpTable.TBL"
    ln -sf "$NOAHMP_DRV/URBPARM.TBL"     "$RUNDIR/URBPARM.TBL"
    ln -sf "$RRTMGP/rrtmgp/data/rrtmgp-data-sw-g224-2018-12-04.nc"          "$RUNDIR/"
    ln -sf "$RRTMGP/rrtmgp/data/rrtmgp-data-lw-g256-2018-12-04.nc"          "$RUNDIR/"
    ln -sf "$RRTMGP/extensions/cloud_optics/rrtmgp-cloud-optics-coeffs-sw.nc" "$RUNDIR/"
    ln -sf "$RRTMGP/extensions/cloud_optics/rrtmgp-cloud-optics-coeffs-lw.nc" "$RUNDIR/"

    echo "[smoke] running $CASE (np = $NP)"

    # How to start the run. The default reproduces the previous behaviour
    # exactly: `mpirun -np N` for more than one rank, and a bare exec for one,
    # which is what a workstation with a normal MPI wants.
    #
    # That default is wrong on a machine whose MPI can only be started through
    # the batch system. On Cray with Slurm there is no usable `mpirun`, and a
    # bare exec inside an allocation fails in PMI rather than running serially,
    # so BOTH branches need redirecting. Set ERF_MPI_LAUNCH to a launcher that
    # takes the rank count as its final argument, e.g.
    #
    #     ERF_MPI_LAUNCH="srun -n" ./run_smoke.sh --exe ... --np 1
    #
    # Leaving it unset changes nothing.
    if [ -n "${ERF_MPI_LAUNCH:-}" ]; then
        read -r -a LAUNCH <<< "$ERF_MPI_LAUNCH"
        LAUNCH+=("$NP")
    elif [ "$NP" -gt 1 ]; then
        LAUNCH=(mpirun -np "$NP")
    else
        LAUNCH=()
    fi

    set +e
    if [ "$NP" -gt 1 ]; then
        # Two overrides are needed to decompose this case, and both are about
        # ERF/Noah-MP rather than about SLUCM:
        #
        #  * Noah-MP asserts every box starts at klo (ERF_NOAHMP_Init.cpp),
        #    so the split must be in x only. blocking_factor has to drop to 1
        #    because 10 cells do not divide by the default 8.
        #  * the 2-D NetCDF plotfile writer hangs on more than one rank -- the
        #    run stalls at the first plt2d write and never returns. The land
        #    NetCDF, which is what check_smoke.py reads, is unaffected, so the
        #    2-D plotfile is simply switched off here.
        #
        # Verified 1 rank vs 2 ranks: all 54 land fields bit-identical.
        ( cd "$RUNDIR" && "${LAUNCH[@]}" "$EXE" inputs_slucm \
              "amr.max_grid_size_x=$MGS_X" amr.max_grid_size_y=10 \
              amr.max_grid_size_z=20 amr.blocking_factor=1 \
              erf.plot2d_int_1=-1 > run.log 2>&1 )
    else
        ( cd "$RUNDIR" && "${LAUNCH[@]}" "$EXE" inputs_slucm > run.log 2>&1 )
    fi
    rc=$?
    set -e
    # A bare Fortran STOP returns 0, so the exit code alone does not prove the
    # run finished -- check_smoke.py re-checks by looking for the expected
    # output files and step count.
    echo "[smoke] $CASE exit code $rc"
    if [ $rc -ne 0 ]; then
        echo "[smoke] --- tail of $RUNDIR/run.log ---"
        tail -30 "$RUNDIR/run.log"
        exit $rc
    fi
done

if [ "$RUN_CHECK" -eq 1 ]; then
    python3 "$SCRIPT_DIR/check_smoke.py" --work "$WORK"
else
    echo "[smoke] runs complete in $WORK (checker skipped)"
fi
